---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  cnf.example.com/vrouter: ""

resources:
#- 03-create-namespace.yaml
- 03-network-definition.yaml
- 10-frr-configmap.yaml
- 10-frr-configmap2.yaml
- 10-frr-pod.yaml